const easyQuestions = [
  {
    questionText: 'Who painted the Mona Lisa?',
    options: [
      { optionText: 'Vincent Van Gogh', isCorrect: false },
      { optionText: 'Pablo Picasso', isCorrect: false },
      { optionText: 'Leonardo da Vinci', isCorrect: true },
      { optionText: 'Michelangelo', isCorrect: false },
    ],
    correctAnswer: 'Leonardo da Vinci',
    helperImage: 'image_url_for_mona_lisa_question',
    timeLimit: 30,
    roundNumber: 1,
  },
  {
    questionText: 'What is the capital of France?',
    options: [
      { optionText: 'Berlin', isCorrect: false },
      { optionText: 'Paris', isCorrect: true },
      { optionText: 'London', isCorrect: false },
      { optionText: 'Rome', isCorrect: false },
    ],
    correctAnswer: 'Paris',
    helperImage: 'image_url_for_paris_question',
    timeLimit: 30,
    roundNumber: 2,
  },
  {
    questionText: 'Which planet is known as the Red Planet?',
    options: [
      { optionText: 'Jupiter', isCorrect: false },
      { optionText: 'Mars', isCorrect: true },
      { optionText: 'Venus', isCorrect: false },
      { optionText: 'Saturn', isCorrect: false },
    ],
    correctAnswer: 'Mars',
    helperImage: 'image_url_for_mars_question',
    timeLimit: 30,
    roundNumber: 3,
  },
  {
    questionText: 'What is the largest mammal in the world?',
    options: [
      { optionText: 'Elephant', isCorrect: false },
      { optionText: 'Blue Whale', isCorrect: true },
      { optionText: 'Giraffe', isCorrect: false },
      { optionText: 'Hippopotamus', isCorrect: false },
    ],
    correctAnswer: 'Blue Whale',
    helperImage: 'image_url_for_blue_whale_question',
    timeLimit: 30,
    roundNumber: 4,
  },
  {
    questionText: 'In which year did the Titanic sink?',
    options: [
      { optionText: '1912', isCorrect: true },
      { optionText: '1905', isCorrect: false },
      { optionText: '1915', isCorrect: false },
      { optionText: '1920', isCorrect: false },
    ],
    correctAnswer: '1912',
    helperImage: 'image_url_for_titanic_question',
    timeLimit: 30,
    roundNumber: 5,
  },
  {
    questionText: 'What is the boiling point of water?',
    options: [
      { optionText: '100 degrees Celsius', isCorrect: true },
      { optionText: '90 degrees Celsius', isCorrect: false },
      { optionText: '120 degrees Celsius', isCorrect: false },
      { optionText: '80 degrees Celsius', isCorrect: false },
    ],
    correctAnswer: '100 degrees Celsius',
    helperImage: 'image_url_for_boiling_water_question',
    timeLimit: 30,
    roundNumber: 6,
  },
  {
    questionText: 'Which animal is known as the King of the Jungle?',
    options: [
      { optionText: 'Elephant', isCorrect: false },
      { optionText: 'Lion', isCorrect: true },
      { optionText: 'Tiger', isCorrect: false },
      { optionText: 'Giraffe', isCorrect: false },
    ],
    correctAnswer: 'Lion',
    helperImage: 'image_url_for_lion_question',
    timeLimit: 30,
    roundNumber: 7,
  },
  {
    questionText: 'How many colors are there in a rainbow?',
    options: [
      { optionText: '5', isCorrect: false },
      { optionText: '7', isCorrect: true },
      { optionText: '6', isCorrect: false },
      { optionText: '8', isCorrect: false },
    ],
    correctAnswer: '7',
    helperImage: 'image_url_for_rainbow_question',
    timeLimit: 30,
    roundNumber: 8,
  },
  {
    questionText: 'What is the hardest natural substance on Earth?',
    options: [
      { optionText: 'Gold', isCorrect: false },
      { optionText: 'Iron', isCorrect: false },
      { optionText: 'Diamond', isCorrect: true },
      { optionText: 'Silver', isCorrect: false },
    ],
    correctAnswer: 'Diamond',
    helperImage: 'image_url_for_diamond_question',
    timeLimit: 30,
    roundNumber: 9,
  },
  {
    questionText: 'What gas do plants absorb from the air during photosynthesis?',
    options: [
      { optionText: 'Oxygen', isCorrect: false },
      { optionText: 'Carbon Dioxide', isCorrect: true },
      { optionText: 'Nitrogen', isCorrect: false },
      { optionText: 'Hydrogen', isCorrect: false },
    ],
    correctAnswer: 'Carbon Dioxide',
    helperImage: 'image_url_for_photosynthesis_question',
    timeLimit: 30,
    roundNumber: 10,
  },
];

module.exports = easyQuestions;
